# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jovanovic Lab
email: mj2794@columbia.edu
phone: "(212)-854-4581"
description: > # this means to ignore newlines until "baseurl:"
  This is the official website for the Jovanovic Lab at Columbia 
  University. We're an academic lab studying post-transcriptional
  and post-translational regulation located in the Fairchild Center
  in Columbia University's Morningside campus.
baseurl: ""
url: https://mjlab-columbia.github.io

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
